### ISSUE TITLE
Pinch-to-zoom causing jankiness on tablets

### ISSUE THREAD

**Issue by RobinKwong** [ft-interactive/seasonal-appeal-2015#13]
is there a way to either disable it or do something with max/min widths to stop this from happening?

**Comment by i-like-robots** [comment]
We've disabled zoom changed our cut the mustard test so Safari =< 7 will fail and receive the core experience. The reason we decided to take this measure is because the implementation of viewport units is [very broken](https://github.com/scottjehl/Device-Bugs/issues/36) in that browser.
